### CREATE A ONLINE BOOK
POST  http://localhost:3000/books
Content-Type: application/json

{
  "title": "Book Title",
  "overview": "An engaging overview.",
  "rating": 4.5,
  "author": "Author Name",
  "genres": ["Fiction", "Adventure"],
  "price": 19.99
}

####GET ALL THE BOOKS
GET http://localhost:3000/books


###GET A SINGLE BOOK
GET  http://localhost:3000/books/1
#### UPDDATE A BOOK
PUT http://localhost:3000/books/1
Content-Type: application/json

{
  "title": "Updated Title",
  "overview": "Updated overview.",
  "rating": 4.7,
  "author": "Updated Author",
  "genres": ["Drama", "History"],
  "price": 22.99
}

###DELETE A BOOK
DELETE  http://localhost:3000/books/1
